# Generated by Django 6.0 on 2025-12-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_updates',
            new_name='is_updated',
        ),
    ]
