# Generated by Django 6.0 on 2025-12-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_is_updates_article_is_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_updated',
            new_name='is_updates',
        ),
    ]
