# Generated by Django 6.0 on 2025-12-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_is_updated_article_is_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
